# Site settings
title: Raison D'souza
description: 'Developer  -  Cyclist'
url: 'http://localhost:4000/jekyll-uno'
baseurl: '/jekyll-uno/'
# google_analytics: 'UA-XXXXXX-X'

author:
  name: 'Raison Dsouza'
  email: raisondsouza@gmail.com
  twitter_username: rdsoze
  github_username:  rdsoze
  linkedin_username:  rdsoze
  strava: 3661047

image_path: "https://s3-us-west-2.amazonaws.com/rdsoze/blog_images"

# Build settings
destination: _site
paginate: 10
permalink: /:year-:title/
markdown: kramdown
highlighter: pygments

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
